mysite/dobble/urls.py
from django.conf.urls import url
from . import views

app_name = 'dobble'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^players/$', views.players, name='players'),
    url(r'^addPlayer/$', views.addPlayer, name='addPlayer'),
    url(r'^removePlayer/$', views.removePlayer, name='removePlayer'),
    url(r'^addRound/$', views.addRound, name='addRound'),
    url(r'^removeRound/$', views.subtractRound, name='subtractRound'),
    url(r'^reset/$', views.reset, name='reset'),
    url(r'^savePlayers/$', views.savePlayers, name='savePlayers'),
    url(r'^game/$', views.game, name='game'),
    url(r'^updateScores/$', views.updateScores, name='updateScores'),
]

mysite/films/urls.py
from django.conf.urls import url
from . import views

app_name = 'films'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^watched/$', views.watched, name='watched'),
    url(r'^unwatched/$', views.unwatched, name='unwatched'),
    url(r'^$', views.index, name='all'),
    url(r'^addfilm/$', views.addFilm, name='addfilm'),
    url(r'^addfilm/(?P<notice>[^\/]+)', views.addFilm, name='addfilm'),
    url(r'^add/$', views.add, name='add'),
    url(r'^toggleWatched/$', views.toggleWatched, name='toggleWatched'),
    url(r'^updateFilm/$', views.updateFilm, name='updateFilm'),
    url(r'^deleteFilm/$', views.deleteFilm, name='deleteFilm'),
]

mysite/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login_user, name='login'),
]

mysite/mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.contrib.auth.views import login,logout

urlpatterns = [
    url(r'^accounts/logout/$', logout),
    url(r'^', include('home.urls')),
    url(r'^films/', include('films.urls')),
    url(r'^dobble/', include('dobble.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/home/models.py
from django.db import models

# Create your models here.

mysite/home/views.py
from django.http import *
from django.shortcuts import render_to_response,redirect, render
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

def login_user(request):
    logout(request)
    username = password = ''
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
    context={}

    return render(request, 'home/login.html', context)


@login_required(login_url='/login/')
def index(request):
    context={}
    return render(request, 'home/index.html', context)

mysite/home/templates/home/index.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/static/css/w3.css">
<link rel="stylesheet" href="/static/css/w3-theme-black.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
.w3-sidenav a,.w3-sidenav h4 {padding: 12px;}
.w3-navbar li a {
    padding-top: 12px;
    padding-bottom: 12px;
}
</style>
<head>
    <title>Welcome</title>
</head>

<body>

    <div class="w3-top">
        <ul class="w3-navbar w3-theme w3-top w3-left-align w3-large">
                <li class="w3-opennav w3-right w3-hide-large">
                    <a class="w3-hover-white w3-large w3-theme-l1" href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>
                </li>
                <li><a href="#" class="w3-theme-l1">Conor's Apps</a></li>
        </ul>
        </div>

            <!-- Sidenav -->
        <nav class="w3-sidenav w3-collapse w3-theme-l5 w3-animate-left" style="z-index:3;width:250px;margin-top:51px;" id="mySidenav">
          <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="close menu">
            <i class="fa fa-remove"></i>
          </a>
          <h4><b>Menu</b></h4>
            <a href="{% url 'films:index'%}">Film Tracker</a>
            <a href="{% url 'dobble:index'%}">Dobbles</a>
            <a href="/accounts/logout/">Logout</a>
        </nav>

        <!-- Overlay effect when opening sidenav on small screens -->
        <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

        <div class="w3-main" style="margin-left:300px;max-width:800px">
            <div class="w3-row w3-padding-64">
                <h1 class="w3-text-teal">Welcome!</h1>
                Select an app from the menu.
            </div>
        </div>
    </div>
<script>
// Get the Sidenav
var mySidenav = document.getElementById("mySidenav");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidenav, and add overlay effect
function w3_open() {
    if (mySidenav.style.display === 'block') {
        mySidenav.style.display = 'none';
        overlayBg.style.display = "none";
    } else {
        mySidenav.style.display = 'block';
        overlayBg.style.display = "block";
    }
}

// Close the sidenav with the close button
function w3_close() {
    mySidenav.style.display = "none";
    overlayBg.style.display = "none";
}
</script>
</body>

</html>

mysite/home/templates/home/login.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/static/css/w3.css">
<link rel="stylesheet" href="/static/css/w3-theme-black.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
.w3-sidenav a,.w3-sidenav h4 {padding: 12px;}
.w3-navbar li a {
    padding-top: 12px;
    padding-bottom: 12px;
}
</style>
<head>
    <title>Login</title>
</head>
<body>
        <div class="w3-top">
        <ul class="w3-navbar w3-theme w3-top w3-left-align w3-large">
                <li><a href="#" class="w3-theme-l1">Login</a></li>
        </ul>
        </div>

        <div class="w3-main" style="max-width:800px">
            <div class="w3-row w3-padding-64">
                <form class="w3-container" name="LoginForm" action="/login/" method="post">
                {% csrf_token %}
                {% if next %}
                    <input type="hidden" name="next" value="{{ next }}" />
                {% endif %}
                    <label class="w3-label for="username">Username</label>
                    <input class="w3-input w3-border" type="text" id="username" name="username"  placeholder="Username">

                    <label class="w3-label for="password">Password</label>
                    <input class="w3-input w3-border" type="password" name="password" id="password" placeholder="Password">

                <br/><button class="w3-btn w3-teal w3-round" type="submit" class="btn">Login</button>
                </form>
        </div>
        </div>
</body>
</html>