mysite/films/urls.py
from django.conf.urls import url
from . import views

app_name = 'films'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^watched/$', views.watched, name='watched'),
    url(r'^unwatched/$', views.unwatched, name='unwatched'),
    url(r'^$', views.index, name='all'),
    url(r'^addfilm/$', views.addFilm, name='addfilm'),
    url(r'^addfilm/(?P<notice>[^\/]+)', views.addFilm, name='addfilm'),
    url(r'^add/$', views.add, name='add'),
    url(r'^toggleWatched/$', views.toggleWatched, name='toggleWatched'),
    url(r'^updateFilm/$', views.updateFilm, name='updateFilm'),
    url(r'^deleteFilm/$', views.deleteFilm, name='deleteFilm'),
]

mysite/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login_user, name='login'),
]

mysite/mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.contrib.auth.views import login,logout

urlpatterns = [
    url(r'^accounts/logout/$', logout),
    url(r'^', include('home.urls')),
    url(r'^films/', include('films.urls')),
    url(r'^dobble/', include('dobble.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/films/models.py
from django.db import models

class Film(models.Model):
    class Meta:
        ordering = ('name',)
    name = models.CharField(max_length=200)
    genre = models.CharField(max_length=200, default='', blank=True)
    year = models.IntegerField(default=0)
    runtime = models.IntegerField(default=0)
    imdb_id = models.TextField(default='', blank=True)

    def convertHoursAndMinutesToMinutes(self, duration):
        split_hours = duration.split('h')
        if len(split_hours) == 1:
            hours = 0
            split_minutes = split_hours[0].split('min')
        else:
            hours = split_hours[0].strip()
            split_minutes = split_hours[1].split('min')

        minutes = split_minutes[0].strip()
        runtime = int(hours) * 60 + int(minutes)
        return runtime

    def __str__(self):
        return str(self.id) + ": " + self.name

    class Meta:
        ordering = ('name',)

class UserFilm(models.Model):
    film = models.ForeignKey(Film)
    user_id = models.TextField(default='')
    watched = models.BooleanField(default=False)

    def __str__(self):
        return self.user_id + ": " + str(self.film) + ": " + self.film.name

mysite/films/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Film, UserFilm
from .imdb import getFilmName, updateFilmInfo, getIMDBid


@login_required(login_url='/login/')
def index(request):
    userFilms = UserFilm.objects.filter(user_id=request.user.id).order_by('film')
    context = {
        'title': 'All',
        'films': userFilms,
    }
    return render(request, 'films/watched_unwatched.html', context)


@login_required(login_url='/login/')
def watched(request):
    userFilms = UserFilm.objects.filter(watched=True, user_id=request.user.id).order_by('film')
    context = {
        'title': 'Watched',
        'films': userFilms,
    }
    return render(request, 'films/watched_unwatched.html', context)


@login_required(login_url='/login/')
def unwatched(request):
    userFilms = UserFilm.objects.filter(watched=False, user_id=request.user.id).order_by('film')

    context = {
        'title': 'Unwatched',
        'films': userFilms,
    }
    return render(request, 'films/watched_unwatched.html', context)


@login_required(login_url='/login/')
def addFilm(request, notice=None):
    name = request.GET.get('name', '')
    watched = request.GET.get('watched', '')
    imdb_id = request.GET.get('imdb', '')
    if imdb_id != '':
        name = getFilmName(imdb_id)
    if watched != "True":
        watched = ''

    context = {
        'title': 'Watched',
        'notice': notice,
        'name': name,
        'watched': watched,
        'imdb_id': imdb_id,
    }
    return render(request, 'films/add_film.html', context)


@login_required(login_url='/login/')
def add(request):
    try:
        if request.POST['filmwatched'] == 'on':
            watched_film = True
        else:
            watched_film = False
    except (KeyError):
        watched_film = False
    imdb = request.POST['imdb']
    if imdb == '':
        imdb = getIMDBid(request.POST['name'])

    if len(Film.objects.filter(imdb_id=imdb)) == 0:
        f = Film(imdb_id=imdb)
        f.save()
        updateFilmInfo(f)
        print(Film.objects.all())
    else:
        f = Film.objects.get(imdb_id=imdb)  # Will throw an error if there are multiple films

    user_id = request.user.id

    if len(f.userfilm_set.filter(user_id=user_id)) == 0:
        f.userfilm_set.create(user_id=request.user.id, watched=watched_film)
        message = request.POST['name'] + " has been added!"
    else:
        message = "Film already exists and was not added!"
        print("Film already in users list")

    print(Film.objects.all())
    print(f.userfilm_set.all())

    return HttpResponseRedirect(reverse('films:addfilm', args=(message,)))


@login_required(login_url='/login/')
def toggleWatched(request):
    print("Toggle")
    film = UserFilm.objects.get(film_id=request.POST['id'], user_id=request.user.id)
    if film.watched == False:
        film.watched = True
    else:
        film.watched = False
    film.save()

    redirect = request.POST['redirect']
    return HttpResponseRedirect(reverse('films:' + redirect.lower()))


@login_required(login_url='/login/')
def updateFilm(request):
    print("Updated")
    film_id = request.POST['id']
    film = Film.objects.get(id=film_id)
    updateFilmInfo(film)

    redirect = request.POST['redirect']
    return HttpResponseRedirect(reverse('films:' + redirect.lower()))


@login_required(login_url='/login/')
def deleteFilm(request):  # When a user is deleted, all the users films need to be too
    film = UserFilm.objects.get(film_id=request.POST['id'], user_id=request.user.id)
    film.delete()

    redirect = request.POST['redirect']
    return HttpResponseRedirect(reverse('films:' + redirect.lower()))

mysite/films/templates/films/add_film.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/static/css/w3.css">
<link rel="stylesheet" href="/static/css/w3-theme-black.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
.w3-sidenav a,.w3-sidenav h4 {padding: 12px;}
.w3-navbar li a {
    padding-top: 12px;
    padding-bottom: 12px;
}
</style>
<head>
    <title>Film Tracker</title>
</head>

<body>
<div class="w3-top">
        <ul class="w3-navbar w3-theme w3-top w3-left-align w3-large">
                <li class="w3-opennav w3-right w3-hide-large">
                    <a class="w3-hover-white w3-large w3-theme-l1" href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>
                </li>
                <li><a href="#" class="w3-theme-l1">Film Tracker</a></li>
        </ul>
        </div>

    <!-- Sidenav -->
        <nav class="w3-sidenav w3-collapse w3-theme-l5 w3-animate-left" style="z-index:3;width:250px;margin-top:51px;" id="mySidenav">
          <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="close menu">
            <i class="fa fa-remove"></i>
          </a>
          <h4><b>Menu</b></h4>
            <a href="{% url 'films:index'%}">All Films</a>
            <a href="{% url 'films:watched'%}">Watched Films</a>
            <a href="{% url 'films:unwatched'%}">Unwatched Films</a>
            <a href="{% url 'home:index'%}">Exit App</a>
            <a href="/accounts/logout/">Logout</a>
        </nav>

        <!-- Overlay effect when opening sidenav on small screens -->
        <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<div class="w3-main" style="margin-left:300px;max-width:800px">
            <div class="w3-row w3-padding-64">
                <h1 class="w3-text-teal">Add film</h1>

            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

            <form class="w3-container" action="{% url 'films:add'%}" method="post">
                {% csrf_token %}
                <label class="w3-label" for="name">Film name</label>
                <input class="w3-input w3-border" type="string" name="name" id="name" value="{{ name }}"/>
                <input class="w3-check"  type="checkbox" name="filmwatched" id="filmwatched" {% if watched %} checked {% endif %}/>
                <label class="w3-label" for="filmwatched">Watched?</label><br/><br/>
                <input type="hidden" name="imdb" id="imdb" value="{{ imdb_id }}"/>

                <input class="w3-btn w3-teal w3-round"type="submit" value="Add"/>
                <br/>
                {% if notice %}<p>{{ notice }}</p>{% endif %}
            </form>

            </div>
</div>
<script>
// Get the Sidenav
var mySidenav = document.getElementById("mySidenav");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidenav, and add overlay effect
function w3_open() {
    if (mySidenav.style.display === 'block') {
        mySidenav.style.display = 'none';
        overlayBg.style.display = "none";
    } else {
        mySidenav.style.display = 'block';
        overlayBg.style.display = "block";
    }
}

// Close the sidenav with the close button
function w3_close() {
    mySidenav.style.display = "none";
    overlayBg.style.display = "none";
}
</script>
</body>
</html>

mysite/films/templates/films/watched_unwatched.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/static/css/w3.css">
<link rel="stylesheet" href="/static/css/w3-theme-black.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
.w3-sidenav a,.w3-sidenav h4 {padding: 12px;}
.w3-navbar li a {
    padding-top: 12px;
    padding-bottom: 12px;
}
</style>
<head>
    <title>Film Tracker</title>
</head>

<body>

    <div class="w3-top">
        <ul class="w3-navbar w3-theme w3-top w3-left-align w3-large">
                <li class="w3-opennav w3-right w3-hide-large">
                    <a class="w3-hover-white w3-large w3-theme-l1" href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>
                </li>
                <li><a href="#" class="w3-theme-l1">Film Tracker</a></li>
        </ul>
        </div>

            <!-- Sidenav -->
        <nav class="w3-sidenav w3-collapse w3-theme-l5 w3-animate-left" style="z-index:3;width:250px;margin-top:51px;" id="mySidenav">
          <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="close menu">
            <i class="fa fa-remove"></i>
          </a>
          <h4><b>Menu</b></h4>
            <a href="{% url 'films:index'%}">All Films</a>
            <a href="{% url 'films:watched'%}">Watched Films</a>
            <a href="{% url 'films:unwatched'%}">Unwatched Films</a>
            <a href="{% url 'home:index'%}">Exit App</a>
            <a href="/accounts/logout/">Logout</a>
        </nav>

        <!-- Overlay effect when opening sidenav on small screens -->
        <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

        <div class="w3-main" style="margin-left:300px;max-width:800px">
            <div class="w3-row w3-padding-64">

                <h1 class="w3-text-teal">{{ title }} films</h1>
                {% if films %}
                <table class="w3-table w3-bordered w3-hoverable" style="display: block;overflow-x: auto;">
                    <tr>
                        <th>Name</th>
                        <th>Year</th>
                        <th>Runtime</th>
                        <th>Genre</th>
                        {% if title == "All" %}
                        <th>Watched</th>
                        {% endif %}
                        <th></th>
                        <th></th>
                        <th></th>

                    </tr>
                    {% for film in films %}
                    <tr>
                        <td><a {% if film.imdb_id != ''%}href="http://www.imdb.com/title/{{film.film.imdb_id}}"{%endif%}>{{ film.film.name }}</a></td>
                        <td>{{ film.film.year }}</td>
                        <td>{{ film.film.runtime }}</td>
                        <td>{{ film.film.genre }}</td>
                        {% if title == "All" %}
                        <td>{{ film.watched }}</td>
                        {% endif %}

                        <td>
                            <form action="{% url 'films:toggleWatched'%}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="id" id="toggle_id" value="{{ film.film.id }}" />
                                <input type="hidden" name="redirect" id="toggle_redirect" value="{{ title }}" />
                                <input type="submit" class="w3-btn w3-btn-floating w3-teal" value={% if title == "Unwatched" %} "M"{% else %} {% if title == "Watched" %} "M"{% else %} "T"{% endif %}{% endif %}/>
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'films:updateFilm'%}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="id" id="update_id" value="{{ film.film.id }}" />
                                <input type="hidden" name="redirect" id="update_redirect" value="{{ title }}" />
                                <input type="submit" class="w3-btn w3-btn-floating w3-teal" value="U" />
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'films:deleteFilm'%}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="id" id="delete_id" value="{{ film.film.id }}" />
                                <input type="hidden" name="redirect" id="delete_redirect" value="{{ title }}" />
                                <input type="submit" class="w3-btn w3-btn-floating w3-teal" value="D" />
                            </form>
                        </td>

                    </tr>
                    {% endfor %}
                </table>
                {% else %}
                <p>No {{ title.lower }} films</p>
                {% endif %}
                <br/>
                <a class="w3-btn w3-teal w3-round" style="margin-left:10px" href="{% url 'films:addfilm'%}?watched={% if title == "Watched" %}True{% else %}False{% endif %}">Add film</a><br/>
            </div>
        </div>
    </div>
<script>
// Get the Sidenav
var mySidenav = document.getElementById("mySidenav");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidenav, and add overlay effect
function w3_open() {
    if (mySidenav.style.display === 'block') {
        mySidenav.style.display = 'none';
        overlayBg.style.display = "none";
    } else {
        mySidenav.style.display = 'block';
        overlayBg.style.display = "block";
    }
}

// Close the sidenav with the close button
function w3_close() {
    mySidenav.style.display = "none";
    overlayBg.style.display = "none";
}
</script>
</body>

</html>