mysite/dobble/urls.py
from django.conf.urls import url
from . import views

app_name = 'dobble'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^players/$', views.players, name='players'),
    url(r'^addPlayer/$', views.addPlayer, name='addPlayer'),
    url(r'^removePlayer/$', views.removePlayer, name='removePlayer'),
    url(r'^addRound/$', views.addRound, name='addRound'),
    url(r'^removeRound/$', views.subtractRound, name='subtractRound'),
    url(r'^reset/$', views.reset, name='reset'),
    url(r'^savePlayers/$', views.savePlayers, name='savePlayers'),
    url(r'^game/$', views.game, name='game'),
    url(r'^updateScores/$', views.updateScores, name='updateScores'),
]

mysite/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login_user, name='login'),
]

mysite/mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.contrib.auth.views import login,logout

urlpatterns = [
    url(r'^accounts/logout/$', logout),
    url(r'^', include('home.urls')),
    url(r'^films/', include('films.urls')),
    url(r'^dobble/', include('dobble.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/dobble/models.py
from datetime import datetime
from django.db import models


class Game(models.Model):
    date = models.DateTimeField(default=datetime.now, blank=True)
    number_of_players = models.IntegerField(default=1)
    number_of_rounds = models.IntegerField(default=1)


class Player(models.Model):
    name = models.CharField(max_length=200, default="")
    number = models.IntegerField(default=0)
    total_score = models.IntegerField(default=0)
    game = models.ForeignKey(Game, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('number',)

class Score(models.Model):
    round = models.IntegerField(default=0)
    cards = models.IntegerField(default=0)
    score = models.IntegerField(default=0)
    tiebreak = models.BooleanField(default=False)
    tiebreak2 = models.BooleanField(default=False)
    minigame = models.IntegerField(default=0)
    player = models.ForeignKey(Player, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return str(self.round) + "," + str(self.cards) + "," + str(self.score) + "," + str(self.tiebreak)

mysite/dobble/views.py
from django.db.models import Max, Min, Sum
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Game, Player, Score


# Create your views here.
def index(request):
    players = request.GET.get('players', '')
    if players == '':
        players = 1
    print(players)
    context = {
        'players': range(1, int(players) + 1),
        'title': 'All',
    }
    return render(request, 'dobble/players.html', context)


def players(request):
    game = Game.objects.last()
    if game == None:
        game = Game.objects.create()
        game.save()
    number_of_players = game.number_of_players
    players = [x.name for x in game.player_set.all().order_by('number')]
    playerrange = range(1, number_of_players + 1)
    for x in playerrange:
        try:
            players[x - 1]
        except IndexError:
            players.append('')

    print(players)
    context = {
        'range': playerrange,
        'players': players,
        'game': game,
    }
    return render(request, 'dobble/players.html', context)


def addPlayer(request):
    game = Game.objects.last()
    number_of_players = game.number_of_players
    game.number_of_players = number_of_players + 1
    game.save()
    return HttpResponseRedirect(reverse('dobble:players'))


def removePlayer(request):
    game = Game.objects.last()
    number_of_players = game.number_of_players
    game.number_of_players = number_of_players - 1
    game.save()
    return HttpResponseRedirect(reverse('dobble:players'))


def addRound(request):
    game = Game.objects.last()
    number_of_rounds = game.number_of_rounds
    game.number_of_rounds = number_of_rounds + 1
    game.save()
    return HttpResponseRedirect(reverse('dobble:players'))


def subtractRound(request):
    game = Game.objects.last()
    number_of_rounds = game.number_of_rounds
    game.number_of_rounds = number_of_rounds - 1
    game.save()
    return HttpResponseRedirect(reverse('dobble:players'))


def savePlayers(request):
    game = Game.objects.last()
    number_of_players = game.number_of_players
    for x in range(1, number_of_players + 1):
        try:
            p = game.player_set.all()[x - 1]
            print(p)
            if p.name != request.POST['name' + str(x)]:
                p.name = request.POST['name' + str(x)]
                p.number = x
                p.save()
        except IndexError:
            p = Player(name=request.POST['name' + str(x)])
            p.number = x
            p.save()
            game.player_set.add(p)
            game.save()
        for y in range(1, game.number_of_rounds + 1):
            s, created = Score.objects.get_or_create(player=p, round=y)
            s.save()
    return HttpResponseRedirect(reverse('dobble:players'))


def game(request):
    game = Game.objects.last()
    if game == None:
        game = Game.objects.create()
        game.save()

    players = game.player_set.all().order_by('number')
    print(players)
    playerrange = range(1, game.number_of_players + 1)
    roundrange = range(1, game.number_of_rounds + 1)
    scores = []
    for x in roundrange:
        temp = [score for score in Score.objects.filter(round=x)]
        scores.append(temp)
        # print(temp)

    print(scores)
    context = {
        'playerrange': playerrange,
        'roundrange': roundrange,
        'players': players,
        'game': game,
        'scores': scores,
    }
    return render(request, 'dobble/game.html', context)


def updateRound(round):
    scores = Score.objects.filter(round=round)
    minigame = scores[0].minigame
    # print(scores)
    # print(scores.aggregate(Max('cards')))
    # print(minigame)
    if minigame == 1:
        for s in scores:
            s.score = s.cards
            s.save()
        max = scores.aggregate(Max('cards'))['cards__max']
        winners = scores.filter(cards=max)
        if len(winners) == 1:
            winners[0].score += 5
            winners[0].save()
        else:
            winners = winners.filter(tiebreak=True)
            if len(winners) == 1:
                winners[0].score += 5
                winners[0].save()
    elif minigame == 2:
        min = scores.aggregate(Min('cards'))['cards__min']
        winners = scores.filter(cards=min)
        if len(winners) == 1:
            winners[0].score = 10
            winners[0].save()

        max = scores.aggregate(Max('cards'))['cards__max']
        losers = scores.filter(cards=max)
        if len(losers) == 1:
            losers[0].score = -20
            losers[0].save()
    elif minigame == 3:
        for s in scores:
            s.score = 0
            s.save()
        min = scores.aggregate(Min('cards'))['cards__min']
        lowest = scores.filter(cards=min)
        other = scores.filter(cards__gt=min)
        if len(lowest) == 1:
            lowest[0].score = 20
            lowest[0].save()
            min = other.aggregate(Min('cards'))['cards__min']
            second_lowest = other.filter(cards=min)
            if len(second_lowest) == 1:
                second_lowest[0].score = 10
                second_lowest[0].save()
            else:
                second_lowest = second_lowest.filter(tiebreak=True)
                if len(second_lowest) == 1:
                    second_lowest[0].score = 10
                    second_lowest[0].save()
        elif len(lowest) == 2:
            winner = lowest.filter(tiebreak=True)
            if len(winner) == 1:
                winner[0].score = 20
                winner[0].save()

            second = lowest.filter(tiebreak=False)
            if len(second) == 1:
                second[0].score = 10
                second[0].save()
        else:
            winner = lowest.filter(tiebreak=True)
            if len(winner) == 1:
                winner[0].score = 20
                winner[0].save()

            second = lowest.filter(tiebreak2=True)
            if len(second) == 1:
                second[0].score = 10
                second[0].save()
    elif minigame == 4:
        for s in scores:
            s.score = s.cards * -5
            s.save()
    elif minigame == 5:
        for s in scores:
            s.score = s.cards
            s.save()


def updateScores(request):
    game = Game.objects.last()
    number_of_players = game.number_of_players
    number_of_rounds = game.number_of_rounds
    players = game.player_set.all().order_by('number')
    for x in range(1, number_of_players + 1):
        p = players[x - 1]
        for y in range(1, number_of_rounds + 1):
            s, created = Score.objects.get_or_create(player=p, round=y)
            cards_request = request.POST[p.name + ',' + str(y)].split('*')
            if len(cards_request) == 2:
                s.tiebreak = True
            else:
                s.tiebreak = False

            if len(cards_request) > 2:
                s.tiebreak2 = True
            else:
                s.tiebreak2 = False
            s.cards = int(cards_request[0])
            s.minigame = int(request.POST['Minigame' + str(y)])
            s.save()
            p.score_set.add(s)
            p.save()

    for round in range(1, number_of_rounds + 1):
        updateRound(round)

    for x in range(1, number_of_players + 1):
        p = players[x - 1]
        p.total_score = p.score_set.all().aggregate(Sum('score'))['score__sum']
        p.save()
    return HttpResponseRedirect(reverse('dobble:game'))


def reset(request):
    for score in Score.objects.all():
        score.delete()
    for game in Game.objects.all():
        game.delete()

    return HttpResponseRedirect(reverse('dobble:game'))

mysite/dobble/templates/dobble/game.html
{% load index %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/static/css/w3.css">
<link rel="stylesheet" href="/static/css/w3-theme-black.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
.w3-sidenav a,.w3-sidenav h4 {padding: 12px;}
.w3-navbar li a {
    padding-top: 12px;
    padding-bottom: 12px;
}
</style>
<head>
    <title>Dobble!</title>
</head>
<body>
<div class="w3-top">
        <ul class="w3-navbar w3-theme w3-top w3-left-align w3-large">
                <li class="w3-opennav w3-right w3-hide-large">
                    <a class="w3-hover-white w3-large w3-theme-l1" href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>
                </li>
                <li><a href="#" class="w3-theme-l1">Dobble</a></li>
        </ul>
        </div>

    <!-- Sidenav -->
        <nav class="w3-sidenav w3-collapse w3-theme-l5 w3-animate-left" style="z-index:3;width:250px;margin-top:51px;" id="mySidenav">
          <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="close menu">
            <i class="fa fa-remove"></i>
          </a>
          <h4><b>Menu</b></h4>
            <a href="{% url 'dobble:players'%}">Players</a>
            <a href="{% url 'dobble:game'%}">Game</a>
            <a href="{% url 'dobble:game'%}">Conclusion</a>
            <a href="{% url 'home:index'%}">Exit App</a>
            <a href="/accounts/logout/">Logout</a>
        </nav>
        <!-- Overlay effect when opening sidenav on small screens -->
        <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<div class="w3-main" style="margin-left:300px;max-width:800px">
    <div class="w3-row w3-padding-64">
        <h1>Dobble!</h1>

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <table class="w3-table w3-bordered w3-hoverable" style="display: block;overflow-x: auto;">
            <tr>
                <th></th>
                {% for x in playerrange %}
                <th>{{players|index:forloop.counter0}}</th>
                {% endfor %}
                <th/>

            </tr>
                <form action="{% url 'dobble:updateScores'%}" method="post" id="cards">
            {% csrf_token %}
            {% for s in scores %}
            <tr>
                <td>Round {{s.1.round}}</td>
                {% for p in s %}
                    <td><input name="{{p.player.name}},{{p.round}}" id="{{p.player.name}},{{p.round}}" value="{{p.cards}}{%if p.tiebreak == True %}*{% endif %}{%if p.tiebreak2 == True %}**{% endif %}" style="max-width:50px"/></td>
                {% endfor %}
                <td>
                    <select form="cards" name="Minigame{{s.1.round}}" id="Minigame{{p.round}}">
                  <option value="1" {%if s.1.minigame == 1 %}selected{% endif %}>The Towering Inferno</option>
                  <option value="2" {%if s.1.minigame == 2 %}selected{% endif %}>The Well</option>
                  <option value="3" {%if s.1.minigame == 3 %}selected{% endif %}>The Poisoned Gift</option>
                  <option value="4" {%if s.1.minigame == 4 %}selected{% endif %}>The Hot Potato</option>
                  <option value="5" {%if s.1.minigame == 5 %}selected{% endif %}>Gotta Catch Them All</option>
                    </select>
                </td>
            </tr>
            {% endfor %}

        </table>
            <input class="w3-btn w3-teal w3-round" type="submit" value="Update Scores"/>
                </form>

            </br>
            </br>

            <h1>Scores</h1>

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <table class="w3-table w3-bordered w3-hoverable" style="display: block;overflow-x: auto;">

            <tr>
                <th></th>
                {% for x in playerrange %}
                <th>{{players|index:forloop.counter0}}</th>
                {% endfor %}

            </tr>
                <form action="{% url 'dobble:updateScores'%}" method="post">
            {% csrf_token %}
            {% for s in scores %}
            <tr>
                <td>Round {{s.1.round}}</td>
                {% for p in s %}
                    <td>{{p.score}}</td>
                {% endfor %}
            </tr>
            {% endfor %}
            <tr>
                 <td>Total</td>
                {% for x in playerrange %}
                <td>{{players|total:forloop.counter0}}</td>
                {% endfor %}
            </tr>

        </table>
    </div>
</div>
<script>
// Get the Sidenav
var mySidenav = document.getElementById("mySidenav");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidenav, and add overlay effect
function w3_open() {
    if (mySidenav.style.display === 'block') {
        mySidenav.style.display = 'none';
        overlayBg.style.display = "none";
    } else {
        mySidenav.style.display = 'block';
        overlayBg.style.display = "block";
    }
}

// Close the sidenav with the close button
function w3_close() {
    mySidenav.style.display = "none";
    overlayBg.style.display = "none";
}
</script>
</body>
</html>

mysite/dobble/templates/dobble/players.html
{% load index %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/static/css/w3.css">
<link rel="stylesheet" href="/static/css/w3-theme-black.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
.w3-sidenav a,.w3-sidenav h4 {padding: 12px;}
.w3-navbar li a {
    padding-top: 12px;
    padding-bottom: 12px;
}
</style>
<head>
    <title>Dobble!</title>
</head>
<body>
<div class="w3-top">
        <ul class="w3-navbar w3-theme w3-top w3-left-align w3-large">
                <li class="w3-opennav w3-right w3-hide-large">
                    <a class="w3-hover-white w3-large w3-theme-l1" href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>
                </li>
                <li><a href="#" class="w3-theme-l1">Dobble</a></li>
        </ul>
        </div>

    <!-- Sidenav -->
        <nav class="w3-sidenav w3-collapse w3-theme-l5 w3-animate-left" style="z-index:3;width:250px;margin-top:51px;" id="mySidenav">
          <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="close menu">
            <i class="fa fa-remove"></i>
          </a>
          <h4><b>Menu</b></h4>
            <a href="{% url 'dobble:players'%}">Players</a>
            <a href="{% url 'dobble:game'%}">Game</a>
            <a href="{% url 'dobble:game'%}">Conclusion</a>
            <a href="{% url 'home:index'%}">Exit App</a>
            <a href="/accounts/logout/">Logout</a>
        </nav>
        <!-- Overlay effect when opening sidenav on small screens -->
        <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<div class="w3-main" style="margin-left:300px;max-width:800px">
                <div class="w3-row w3-padding-64">


    <h1 class="w3-text-teal">Add players </h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form class="w3-container" action="{% url 'dobble:addPlayer'%}" method="post">
        {% csrf_token %}
        <input class="w3-btn w3-btn-floating w3-teal" type="submit" value="+"/>    <br/>
    </form>
                    <form class="w3-container" action="{% url 'dobble:removePlayer'%}" method="post">
        {% csrf_token %}
        <input class="w3-btn w3-btn-floating w3-teal" type="submit" value="-"/>    <br/>
    </form>
    <form class="w3-container"action="{% url 'dobble:savePlayers'%}" method="post">
        {% for x in range %}
        {% csrf_token %}
        <label class="w3-label" for="name{{x}}">Player {{x}} </label>
        <input class="w3-input w3-border" type="string" name="name{{x}}" id="name{{x}}" value="{{players|index:forloop.counter0}}"/><br/>
        {% if notice %}<p>{{ notice }}</p>{% endif %}
        {% endfor %}
        <input class="w3-btn w3-teal w3-round" type="submit" value="Save"/>    <br/>
    </form>



    <h1 class="w3-text-teal">Add rounds</h1>
    <p>Number of rounds: {{game.number_of_rounds}}</p>
    <form class="w3-container" action="{% url 'dobble:addRound'%}" method="post">
        {% csrf_token %}
        <input class="w3-btn w3-btn-floating w3-teal" type="submit" value="+"/>    <br/>
    </form>
    <form class="w3-container" action="{% url 'dobble:subtractRound'%}" method="post">
        {% csrf_token %}
        <input class="w3-btn w3-btn-floating w3-teal" type="submit" value="-"/>    <br/>
    </form>

     <form class="w3-container" action="{% url 'dobble:reset'%}" method="post">
        {% csrf_token %}
        <input class="w3-btn w3-teal" type="submit" value="Reset"/>    <br/>
    </form>
    </div>
</div>
<script>
// Get the Sidenav
var mySidenav = document.getElementById("mySidenav");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidenav, and add overlay effect
function w3_open() {
    if (mySidenav.style.display === 'block') {
        mySidenav.style.display = 'none';
        overlayBg.style.display = "none";
    } else {
        mySidenav.style.display = 'block';
        overlayBg.style.display = "block";
    }
}

// Close the sidenav with the close button
function w3_close() {
    mySidenav.style.display = "none";
    overlayBg.style.display = "none";
}
</script>
</body>
</html>